name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  # Use Docker Access Token here

    - name: Build and push Docker image
      env:
        IMAGE_NAME: pawpal-help-center-image
        DOCKERFILE_PATH: .
        TAG: latest  # Replace with your desired tag
      run: |
        docker build -t $IMAGE_NAME:$TAG $DOCKERFILE_PATH || exit 1
        docker push $IMAGE_NAME:$TAG || exit 1
