name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      env:
        IMAGE_NAME: pawpal-help-center-image
        DOCKERFILE_PATH: ./path/to/your/Dockerfile
        TAG: latest  # Replace with your desired tag
      run: |
        docker build -t $IMAGE_NAME:$TAG $DOCKERFILE_PATH
        docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:$TAG
